### ISSUE TITLE
Looking for Server Jar

### ISSUE THREAD

**Issue by Xioto** [tedhong9/Noobo#12]
I do not know how to compile all the source code, could @tedhong9 release the server.jar to run the server.

**Comment by tedhong9** [comment]
If you'd like to get the server.jar, just go to the Actions tab and click on a commit. Then, scroll down and click on the link that says `noobo-1.16.5`. You need to be signed in to download the jar, have fun! :D

![image](https://user-images.githubusercontent.com/62223616/114484383-f6b3c480-9bbe-11eb-92e2-80086959023d.png)

**Comment by squishycat92** [comment]
Added build instructions to the README

**Comment by Xioto** [comment]
Cool Thanks
